### ISSUE TITLE
HA no dropped calls

### ISSUE THREAD

**Issue by rbucker** [dougbtv/docker-asterisk#72]
In your presentation you make a no dropped calls claim but never follow up with a design or configuration.... any more details there?

**Comment by dougbtv** [comment]
Thanks for the question... I'm pretty sure I said that it mitigates the failures in the proposed configuration, what you need in front of the cluster is a sip proxy with replicated SIP dialog state, which you can do with kamailio for example, but, I unfortunately never got the time to come back and pull out those configurations, make them public, and present them. In part the scope is big also because of all the database configuration too (which hopefully I mentioned, I think I mentioned that was kinda too big of a scope for the presentation).
